const CARS_AMOUNT_ROAD_LANE1 = 25;

const CARS_AMOUNT_ROAD_LANE2 = 30;

const CARS_AMOUNT_ROAD_LANE3 = 12;

const CARS_AMOUNT_ROAD_LANE4 = 12;

const CARS_AMOUNT_ROAD_LANE5 = 10;

const CARS_AMOUNT_ROAD_LANE6 = 25;

const CARS_AMOUNT_ROAD_LANE7 = 10;

const CARS_AMOUNT_ROAD_LANE8 = 1;

export const CARS_AMOUNT_PER_ROAD_LANE_ARR = [
  CARS_AMOUNT_ROAD_LANE1,
  CARS_AMOUNT_ROAD_LANE2,
  CARS_AMOUNT_ROAD_LANE3,
  CARS_AMOUNT_ROAD_LANE4,
  CARS_AMOUNT_ROAD_LANE5,
  CARS_AMOUNT_ROAD_LANE6,
  CARS_AMOUNT_ROAD_LANE7,
  CARS_AMOUNT_ROAD_LANE8,
];
