const CARS_AMOUNT_ROAD_LANE1 = 0;
const CARS_AMOUNT_ROAD_LANE2 = 0;
const CARS_AMOUNT_ROAD_LANE3 = 0;
const CARS_AMOUNT_ROAD_LANE4 = 0;
const CARS_AMOUNT_ROAD_LANE5 = 0;
const CARS_AMOUNT_ROAD_LANE6 = 0;
const CARS_AMOUNT_ROAD_LANE7 = 0;
const CARS_AMOUNT_ROAD_LANE8 = 0;

export const CARS_AMOUNT_PER_ROAD_LANE_ARR = [
  CARS_AMOUNT_ROAD_LANE1,
  CARS_AMOUNT_ROAD_LANE2,
  CARS_AMOUNT_ROAD_LANE3,
  CARS_AMOUNT_ROAD_LANE4,
  CARS_AMOUNT_ROAD_LANE5,
  CARS_AMOUNT_ROAD_LANE6,
  CARS_AMOUNT_ROAD_LANE7,
  CARS_AMOUNT_ROAD_LANE8,
];
